package clases;
// Generated 12-ene-2020 13:46:03 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pasaje generated by hbm2java
 */
@Entity
@Table(name = "pasaje", catalog = "pt4_reveng")
public class Pasaje implements java.io.Serializable {

	private PasajeId id;
	private Pasajero pasajero;
	private Vuelo vuelo;
	private Short numasiento;
	private String clase;
	private Float pvp;

	public Pasaje() {
	}

	public Pasaje(PasajeId id, Pasajero pasajero, Vuelo vuelo) {
		this.id = id;
		this.pasajero = pasajero;
		this.vuelo = vuelo;
	}

	public Pasaje(PasajeId id, Pasajero pasajero, Vuelo vuelo, Short numasiento, String clase, Float pvp) {
		this.id = id;
		this.pasajero = pasajero;
		this.vuelo = vuelo;
		this.numasiento = numasiento;
		this.clase = clase;
		this.pvp = pvp;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "pasajeroCod", column = @Column(name = "PASAJERO_COD", nullable = false)),
			@AttributeOverride(name = "identificador", column = @Column(name = "IDENTIFICADOR", nullable = false, length = 10)) })
	public PasajeId getId() {
		return this.id;
	}

	public void setId(PasajeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PASAJERO_COD", nullable = false, insertable = false, updatable = false)
	public Pasajero getPasajero() {
		return this.pasajero;
	}

	public void setPasajero(Pasajero pasajero) {
		this.pasajero = pasajero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDENTIFICADOR", nullable = false, insertable = false, updatable = false)
	public Vuelo getVuelo() {
		return this.vuelo;
	}

	public void setVuelo(Vuelo vuelo) {
		this.vuelo = vuelo;
	}

	@Column(name = "NUMASIENTO")
	public Short getNumasiento() {
		return this.numasiento;
	}

	public void setNumasiento(Short numasiento) {
		this.numasiento = numasiento;
	}

	@Column(name = "CLASE", length = 10)
	public String getClase() {
		return this.clase;
	}

	public void setClase(String clase) {
		this.clase = clase;
	}

	@Column(name = "PVP", precision = 12, scale = 0)
	public Float getPvp() {
		return this.pvp;
	}

	public void setPvp(Float pvp) {
		this.pvp = pvp;
	}

}
