package clases;
// Generated 12-ene-2020 13:46:03 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Personal generated by hbm2java
 */
@Entity
@Table(name = "personal", catalog = "pt4_reveng")
public class Personal implements java.io.Serializable {

	private short codigo;
	private String nombre;
	private String categoria;
	private Set<Tripulacion> tripulacions = new HashSet<Tripulacion>(0);

	public Personal() {
	}

	public Personal(short codigo) {
		this.codigo = codigo;
	}

	public Personal(short codigo, String nombre, String categoria, Set<Tripulacion> tripulacions) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.categoria = categoria;
		this.tripulacions = tripulacions;
	}

	@Id

	@Column(name = "CODIGO", unique = true, nullable = false)
	public short getCodigo() {
		return this.codigo;
	}

	public void setCodigo(short codigo) {
		this.codigo = codigo;
	}

	@Column(name = "NOMBRE", length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "CATEGORIA", length = 15)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personal")
	public Set<Tripulacion> getTripulacions() {
		return this.tripulacions;
	}

	public void setTripulacions(Set<Tripulacion> tripulacions) {
		this.tripulacions = tripulacions;
	}

}
