package clases;
// Generated 12-ene-2020 13:46:03 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tripulacion generated by hbm2java
 */
@Entity
@Table(name = "tripulacion", catalog = "pt4_reveng")
public class Tripulacion implements java.io.Serializable {

	private TripulacionId id;
	private Personal personal;
	private Vuelo vuelo;
	private String puesto;

	public Tripulacion() {
	}

	public Tripulacion(TripulacionId id, Personal personal, Vuelo vuelo) {
		this.id = id;
		this.personal = personal;
		this.vuelo = vuelo;
	}

	public Tripulacion(TripulacionId id, Personal personal, Vuelo vuelo, String puesto) {
		this.id = id;
		this.personal = personal;
		this.vuelo = vuelo;
		this.puesto = puesto;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "vueloIdentificador", column = @Column(name = "VUELO_IDENTIFICADOR", nullable = false, length = 10)),
			@AttributeOverride(name = "personalCodigo", column = @Column(name = "PERSONAL_CODIGO", nullable = false)) })
	public TripulacionId getId() {
		return this.id;
	}

	public void setId(TripulacionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERSONAL_CODIGO", nullable = false, insertable = false, updatable = false)
	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VUELO_IDENTIFICADOR", nullable = false, insertable = false, updatable = false)
	public Vuelo getVuelo() {
		return this.vuelo;
	}

	public void setVuelo(Vuelo vuelo) {
		this.vuelo = vuelo;
	}

	@Column(name = "PUESTO", length = 10)
	public String getPuesto() {
		return this.puesto;
	}

	public void setPuesto(String puesto) {
		this.puesto = puesto;
	}

}
