package clases;
// Generated 12-ene-2020 13:46:03 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vuelo generated by hbm2java
 */
@Entity
@Table(name = "vuelo", catalog = "pt4_reveng")
public class Vuelo implements java.io.Serializable {

	private String identificador;
	private String aeropuertoOrigen;
	private String aeropuertoDestino;
	private String tipoVuelo;
	private Date fechaVuelo;
	private Set<Pasaje> pasajes = new HashSet<Pasaje>(0);
	private Set<Tripulacion> tripulacions = new HashSet<Tripulacion>(0);

	public Vuelo() {
	}

	public Vuelo(String identificador) {
		this.identificador = identificador;
	}

	public Vuelo(String identificador, String aeropuertoOrigen, String aeropuertoDestino, String tipoVuelo,
			Date fechaVuelo, Set<Pasaje> pasajes, Set<Tripulacion> tripulacions) {
		this.identificador = identificador;
		this.aeropuertoOrigen = aeropuertoOrigen;
		this.aeropuertoDestino = aeropuertoDestino;
		this.tipoVuelo = tipoVuelo;
		this.fechaVuelo = fechaVuelo;
		this.pasajes = pasajes;
		this.tripulacions = tripulacions;
	}

	@Id

	@Column(name = "IDENTIFICADOR", unique = true, nullable = false, length = 10)
	public String getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(String identificador) {
		this.identificador = identificador;
	}

	@Column(name = "AEROPUERTO_ORIGEN", length = 10)
	public String getAeropuertoOrigen() {
		return this.aeropuertoOrigen;
	}

	public void setAeropuertoOrigen(String aeropuertoOrigen) {
		this.aeropuertoOrigen = aeropuertoOrigen;
	}

	@Column(name = "AEROPUERTO_DESTINO", length = 10)
	public String getAeropuertoDestino() {
		return this.aeropuertoDestino;
	}

	public void setAeropuertoDestino(String aeropuertoDestino) {
		this.aeropuertoDestino = aeropuertoDestino;
	}

	@Column(name = "TIPO_VUELO", length = 15)
	public String getTipoVuelo() {
		return this.tipoVuelo;
	}

	public void setTipoVuelo(String tipoVuelo) {
		this.tipoVuelo = tipoVuelo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_VUELO", length = 10)
	public Date getFechaVuelo() {
		return this.fechaVuelo;
	}

	public void setFechaVuelo(Date fechaVuelo) {
		this.fechaVuelo = fechaVuelo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vuelo")
	public Set<Pasaje> getPasajes() {
		return this.pasajes;
	}

	public void setPasajes(Set<Pasaje> pasajes) {
		this.pasajes = pasajes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vuelo")
	public Set<Tripulacion> getTripulacions() {
		return this.tripulacions;
	}

	public void setTripulacions(Set<Tripulacion> tripulacions) {
		this.tripulacions = tripulacions;
	}

}
